INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('News', 'https://www.nhk.or.jp/rss/news/cat0.xml', 'http://www3.nhk.or.jp/news/', 'NHK主要ニュース');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('News', 'http://feeds.afpbb.com/rss/afpbb/afpbbnews', 'https://www.afpbb.com/', 'AFP通信');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('News', 'http://feeds.cnn.co.jp/rss/cnn/cnn.rdf', 'https://www.cnn.co.jp', 'CNN.co.jp');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('Tech', 'http://feeds.arstechnica.com/arstechnica/index/', 'https://arstechnica.com/', 'Ars Technica');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('Android', 'https://www.androidpolice.com/feed/', 'https://www.androidpolice.com/', 'Android Police');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('Android', 'https://phandroid.com/feed/', 'https://phandroid.com/', 'PHANDROID');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('Misc', 'https://srad.jp/sradjp.rdf', 'https://srad.jp', 'スラド');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('Misc', 'http://natgeo.nikkeibp.co.jp/nng/rss/index.rdf', 'https://natgeo.nikkeibp.co.jp/', 'ナショナルジオグラフィック日本語版');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('Misc', 'https://pc.watch.impress.co.jp/data/rss/1.0/pcw/feed.rdf', 'https://pc.watch.impress.co.jp/', 'インプレスPCウォッチ');
INSERT INTO default_feed (category_name, url, web_url, name) VALUES ('Misc', 'https://akiba-pc.watch.impress.co.jp/data/rss/1.0/ah/feed.rdf', 'https://akiba-pc.watch.impress.co.jp/', 'インプレス AKIBA PC Hotline!');
